[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "python -m http.server 8888"
  targetPort = 8888
  port = 8889
  publish = "."
  autoLaunch = true